# Generated by Django 5.0.7 on 2024-11-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_contactdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetail',
            new_name='Contact',
        ),
    ]
