# Generated by Django 5.0.7 on 2024-11-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_contactdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetail',
            old_name='mobile_number',
            new_name='mobile_no',
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
