# Generated by Django 5.0.7 on 2024-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_mobile_number_contactdetail_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
